Repository seontechnologies/seon-ios-sdk-swift-package, pull requests merged in 2024-12, with the labels that each got.

#11 [UPDATE] 5.4.2 - Update checksum after certificate change
  Package.swift
Labels: BUGFIX, RELEASE

#12 [UPDATE] 5.5.0
  Package.swift
Labels: RELEASE

#13 Update README.md
  README.md
Labels: DOCUMENTATION
